apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: listmonk-mail-service
  description: listmonk mail service running on AWS App Runner
  tags:
    - apprunner
    - aws
    - wyz
spec:
  type: service
  lifecycle: production
  owner: group:wyz
