apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: wyz
  description: Team WYZ responsible for sample services
spec:
  type: team
  profile:
    displayName: WYZ Team
    email: wyz@gmail.com
  children:
    - User:ravish
    - User:druva
