apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ravish
  annotations: 
    backstage.io/email: ravish@nighthack.in
spec:
  profile:
    displayName: Ravish
    email: ravish@nighthack.in
  memberOf: [wyz]
